clockAccessory = true
compassAccessory = true
recoveryCompassAccessory = true
elytraAccessory = true
spyglassAccessory = true
totemOfUndyingAccessory = true
shulkerBoxAccessory = true
calendarAccessory = true
enderChestAccessory = true
arrowAccessory = true
