	[lists.bedrockoid]
		disableSnowUnderTreesIn = []

	[flags.bedrockoid]
		entitySharesFire = true
		fallenTrees = true
		armorStandArms = true
		frostwalkerBoost = true
		canPlantsBeBonemeal = true
		reachAroundPlacement = true
		snowSpawnsUnderTrees = false
		cauldronNaturalFilling = true
		wetSpongesDryOut = true
		shieldActivatesWhenSneaking = false
		snowCoversVines = true
		stopElytraByPressingSpace = true
		shulkersCanBeDyed = true
		snowlogging = true
		fireAspectImprovements = true
		cauldronWaterloggability = true
		snowCoversLeaves = false
		sodiumTurnOffSnowloggability = false
		composterCollisionFix = true
		redstoneConnectsToPiston = true
		sheepFurColorFix = true
